cc_binary(
    name = "001-two_sum",
    srcs = ["001_two-sum.cc"],
    deps = [
    ],
    copts = [
        "-std=c++17",
    ]
)

cc_binary(
    name = "002_add-two-numbers",
    srcs = ["002_add-two-numbers.cc"],
    deps = [
    ],
    copts = [
        "-std=c++17",
    ]
)

cc_binary(
    name = "003_longest-substring-without-repeating-characters",
    srcs = ["003_longest-substring-without-repeating-characters.cc"],
    deps = [
    ],
    copts = [
        "-std=c++17",
    ]
)

cc_binary(
    name = "007_reverse-integer",
    srcs = ["007_reverse-integer.cc"],
    deps = [
    ],
    copts = [
        "-std=c++17",
    ]
)
